#!bin/bash
negro="\e[1;30m" && azul="\e[1;34m" && verde="\e[1;32m" && cian="\e[1;36m" && rojo="\e[1;31m" && purpura="\e[1;35m" && amarillo="\e[1;33m" && blanco="\e[1;37m"

function titulo(){
echo -e "
${azul}	╺┳┓┏━┓┏━┓╻ ╻╻┏ ┏━╸┏━╸┏┓╻┏┓ ┏━┓╺┳╸
${cian}	 ┃┃┣┳┛┃ ┃┃╻┃┣┻┓┃╺┓┣╸ ┃┗┫┣┻┓┃ ┃ ┃ 
${blanco}	╺┻┛╹┗╸┗━┛┗┻┛╹ ╹┗━┛┗━╸╹ ╹┗━┛┗━┛ ╹ 
\e[0m"
}
archs(){
raw="raw.githubusercontent.com" && main="dGllbmRhc3NoCg/upda"
lista="bot.js shell.sh sourcez vps package.json package-lock.json update.sh"
 for i in $lista;do
  packg="$i"
  down=$(wget https://${raw}/${main}/$i)
  echo -e "${verde}INSTALANDO ➜➜ ${amarillo} $i"
  ${down}
 done
}

function update(){
archs
}
function linea(){
echo -e "${rojo}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\e[0m"
}
function carpets(){
mkdir /etc/.bot-dk
cd /etc/.bot-dk
archs
}
packages(){
apt update && apt upgrade && npm install && npm install fix && npm audit fix && npm audit fix --force
}
function texto(){
echo -e "${amarillo}SE INSTALARÁN LOS ARCHIVOS REQUERIDOS, PUEDE QUE TARDE ALGUNOS MINUTOS"
}
clear && clear
linea
titulo
linea
carpets
texto
packages
